import Head from 'next/head'
import Nav from './nav';
import About from './about';
import SocialMediaIcons from './socialMediaIcons';
import avatar from '../public/avatar.jpg';
import Avatar from './avatar';
import WhatIDo from './whatIDo';
import PortfolioCard from './portfolioCard';
import Card from './card';
import PortfolioText from './portfolioText';
import Image from "next/legacy/image";
import { useState } from 'react';


export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  const swtichbgMode = () =>{
    setDarkMode(!darkMode)
  }
  return (
    <>
    <div className={darkMode ? 'dark': ""}>
      <Head>
        <title>Tesfatsion Shiferaw</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <Nav swtichMode = {swtichbgMode}/>        
          <About />
          <SocialMediaIcons />
          <Avatar />
        </section>

        <section>
          <WhatIDo />
          <div className=' lg:flex gap-10'>
            <Card image={avatar} title={"Front-end"}  tools={["Javascript", "React JS", "Next js"]} description={"Creating elegant designs suited for your design theory."}/>
            <Card image={avatar} title={"Back-end "}  tools={["Django Rest Framework", "Illustrator", "figma"]} description={"Creating elegant designs suited for your design theory."}/>
            <Card image={avatar} title={"Android mobile development"}  tools={["Jetpack Compose", "Xml"]} description={"Creating elegant designs suited for your design theory."}/>
          </div>
        </section>
        <section>
          <PortfolioText />
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <PortfolioCard image={avatar} />
            <PortfolioCard image={avatar} />
            <PortfolioCard image={avatar} />
            <PortfolioCard image={avatar} />
          </div>
        </section>
      </main>
      </div>
    </>
  )
}
